### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by lexplatt** [bsdnoobz/web-based-face-detect#1]
Hi, while compiling the face-detect.cpp, I get the following error:

g++ `pkg-config --cflags --libs opencv` face-detect.cpp -o face-detect
/tmp/ccDDga1V.o: In function `main':
face-detect.cpp:(.text+0x39): undefined reference to`cv::CommandLineParser::CommandLineParser(int, char const*_, char const_)'
face-detect.cpp:(.text+0x13b): undefined reference to `cv::CascadeClassifier::CascadeClassifier()'
face-detect.cpp:(.text+0x15f): undefined reference to`cv::CascadeClassifier::load(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
face-detect.cpp:(.text+0x189): undefined reference to `cv::format(char const*, ...)'
face-detect.cpp:(.text+0x1d1): undefined reference to`cv::imread(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
face-detect.cpp:(.text+0x1f9): undefined reference to `cv::format(char const*, ...)'
face-detect.cpp:(.text+0x24a): undefined reference to`cv::_OutputArray::_OutputArray(cv::Mat&)'
face-detect.cpp:(.text+0x262): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
face-detect.cpp:(.text+0x28a): undefined reference to`cv::cvtColor(cv::_InputArray const&, cv::_OutputArray const&, int, int)'
face-detect.cpp:(.text+0x2a2): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
face-detect.cpp:(.text+0x2ba): undefined reference to`cv::_InputArray::_InputArray(cv::Mat const&)'
face-detect.cpp:(.text+0x2d2): undefined reference to `cv::equalizeHist(cv::_InputArray const&, cv::_OutputArray const&)'
face-detect.cpp:(.text+0x33a): undefined reference to`cv::CascadeClassifier::detectMultiScale(cv::Mat const&, std::vector<cv::Rect_<int>, std::allocatorcv::Rect_<int > >&, double, int, int, cv::Size_<int>, cv::Size_<int>)'
face-detect.cpp:(.text+0x372): undefined reference to `cv::format(char const*, ...)'
face-detect.cpp:(.text+0x3e8): undefined reference to`cv::format(char const_, ...)'
face-detect.cpp:(.text+0x4a6): undefined reference to `cv::rectangle(cv::Mat&, cv::Rect_<int>, cv::Scalar_<double> const&, int, int, int)'
face-detect.cpp:(.text+0x4ee): undefined reference to`cv::_InputArray::_InputArray(cv::Mat const&)'
face-detect.cpp:(.text+0x50a): undefined reference to `cv::imwrite(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
face-detect.cpp:(.text+0x546): undefined reference to`cv::_InputArray::_InputArray(cv::Mat const&)'
face-detect.cpp:(.text+0x562): undefined reference to `cv::imwrite(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
face-detect.cpp:(.text+0x5af): undefined reference to`cv::format(char const_, ...)'
face-detect.cpp:(.text+0x642): undefined reference to `cv::CascadeClassifier::~CascadeClassifier()'
face-detect.cpp:(.text+0x7c6): undefined reference to`cv::CascadeClassifier::~CascadeClassifier()'
/tmp/ccDDga1V.o: In function `cv::Mat::~Mat()':
face-detect.cpp:(.text._ZN2cv3MatD2Ev[_ZN2cv3MatD5Ev]+0x2b): undefined reference to`cv::fastFree(void*)'
/tmp/ccDDga1V.o: In function `cv::Mat::clone() const':
face-detect.cpp:(.text._ZNK2cv3Mat5cloneEv[cv::Mat::clone() const]+0x20): undefined reference to`cv::_OutputArray::_OutputArray(cv::Mat&)'
face-detect.cpp:(.text._ZNK2cv3Mat5cloneEv[cv::Mat::clone() const]+0x32): undefined reference to `cv::Mat::copyTo(cv::_OutputArray const&) const'
/tmp/ccDDga1V.o: In function`cv::Mat::release()':
face-detect.cpp:(.text._ZN2cv3Mat7releaseEv[cv::Mat::release()]+0x3b): undefined reference to `cv::Mat::deallocate()'
/tmp/ccDDga1V.o: In function`cv::Mat::operator()(cv::Rect_<int> const&) const':
face-detect.cpp:(.text._ZNK2cv3MatclERKNS_5Rect_IiEE[cv::Mat::operator()(cv::Rect_<int> const&) const]+0x1b): undefined reference to `cv::Mat::Mat(cv::Mat const&, cv::Rect_<int> const&)'
/tmp/ccDDga1V.o: In function`std::basic_string<char, std::char_traits<char>, std::allocator<char> > cv::CommandLineParser::get<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)':
face-detect.cpp:(.text._ZN2cv17CommandLineParser3getISsEET_RKSsb[std::basic_string<char, std::char_traits<char>, std::allocator<char> > cv::CommandLineParser::get<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)]+0x1b): undefined reference to `cv::CommandLineParser::has(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
face-detect.cpp:(.text._ZN2cv17CommandLineParser3getISsEET_RKSsb[std::basic_string<char, std::char_traits<char>, std::allocator<char> > cv::CommandLineParser::get<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)]+0x48): undefined reference to`cv::CommandLineParser::getString(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
face-detect.cpp:(.text._ZN2cv17CommandLineParser3getISsEET_RKSsb[std::basic_string<char, std::char_traits<char>, std::allocator<char> > cv::CommandLineParser::get<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)]+0x6c): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> > cv::CommandLineParser::analizeValue<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'

**Comment by bsdnoobz** [comment]
It looks like your OpenCV version is lower than 2.4.3. Please upgrade to
version 2.4.3 or above.
- Nash

On Fri, Jul 5, 2013 at 10:16 PM, Alex Platter notifications@github.comwrote:

> Hi, while compiling the face-detect.cpp, I get the following error:
> 
> g++ pkg-config --cflags --libs opencv face-detect.cpp -o face-detect
> /tmp/ccDDga1V.o: In function main':
> face-detect.cpp:(.text+0x39): undefined reference tocv::CommandLineParser::CommandLineParser(int,
> char const*_, char const_)'
> face-detect.cpp:(.text+0x13b): undefined reference to
> cv::CascadeClassifier::CascadeClassifier()'
> face-detect.cpp:(.text+0x15f): undefined reference tocv::CascadeClassifier::load(std::basic_string,
> std::allocator > const&)'
> face-detect.cpp:(.text+0x189): undefined reference to cv::format(char
> const_, ...)'
> face-detect.cpp:(.text+0x1d1): undefined reference tocv::imread(std::basic_string,
> std::allocator > const&, int)'
> face-detect.cpp:(.text+0x1f9): undefined reference to cv::format(char
> const_, ...)'
> face-detect.cpp:(.text+0x24a): undefined reference to
> cv::_OutputArray::_OutputArray(cv::Mat&)'
> face-detect.cpp:(.text+0x262): undefined reference to cv::_InputArray::_InputArray(cv::Mat
> const&)'
> face-detect.cpp:(.text+0x28a): undefined reference tocv::cvtColor(cv::_InputArray
> const&, cv::_OutputArray const&, int, int)'
> face-detect.cpp:(.text+0x2a2): undefined reference to
> cv::_OutputArray::_OutputArray(cv::Mat&)'
> face-detect.cpp:(.text+0x2ba): undefined reference tocv::_InputArray::_InputArray(cv::Mat
> const&)'
> face-detect.cpp:(.text+0x2d2): undefined reference to cv::equalizeHist(cv::_InputArray
> const&, cv::_OutputArray const&)'
> face-detect.cpp:(.text+0x33a): undefined reference tocv::CascadeClassifier::detectMultiScale(cv::Mat
> const&, std::vectorcv::Rect_<int, std::allocatorcv::Rect_<int > >&,
> double, int, int, cv::Size_, cv::Size_)'
> face-detect.cpp:(.text+0x372): undefined reference to cv::format(char
> const_, ...)'
> face-detect.cpp:(.text+0x3e8): undefined reference tocv::format(char
> const_, ...)'
> face-detect.cpp:(.text+0x4a6): undefined reference to cv::rectangle(cv::Mat&,
> cv::Rect_<int>, cv::Scalar_<double> const&, int, int, int)'
> face-detect.cpp:(.text+0x4ee): undefined reference tocv::_InputArray::_InputArray(cv::Mat
> const&)'
> face-detect.cpp:(.text+0x50a): undefined reference to cv::imwrite(std::basic_string<char,
> std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray
> const&, std::vector<int, std::allocator<int> > const&)'
> face-detect.cpp:(.text+0x546): undefined reference tocv::_InputArray::_InputArray(cv::Mat
> const&)'
> face-detect.cpp:(.text+0x562): undefined reference to cv::imwrite(std::basic_string<char,
> std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray
> const&, std::vector<int, std::allocator<int> > const&)'
> face-detect.cpp:(.text+0x5af): undefined reference tocv::format(char
> const_, ...)'
> face-detect.cpp:(.text+0x642): undefined reference to
> cv::CascadeClassifier::~CascadeClassifier()'
> face-detect.cpp:(.text+0x7c6): undefined reference to
> cv::CascadeClassifier::~CascadeClassifier()'
> /tmp/ccDDga1V.o: In function cv::Mat::~Mat()':
> face-detect.cpp:(.text._ZN2cv3MatD2Ev[_ZN2cv3MatD5Ev]+0x2b): undefined
> reference tocv::fastFree(void_)'
> /tmp/ccDDga1V.o: In function cv::Mat::clone() const':
> face-detect.cpp:(.text._ZNK2cv3Mat5cloneEv[cv::Mat::clone() const]+0x20):
> undefined reference tocv::_OutputArray::_OutputArray(cv::Mat&)'
> face-detect.cpp:(.text._ZNK2cv3Mat5cloneEv[cv::Mat::clone() const]+0x32):
> undefined reference to cv::Mat::copyTo(cv::_OutputArray const&) const'
> /tmp/ccDDga1V.o: In functioncv::Mat::release()':
> face-detect.cpp:(.text._ZN2cv3Mat7releaseEv[cv::Mat::release()]+0x3b):
> undefined reference to cv::Mat::deallocate()'
> /tmp/ccDDga1V.o: In functioncv::Mat::operator()(cv::Rect_ const&) const':
> face-detect.cpp:(.text._ZNK2cv3MatclERKNS_5Rect_IiEE[cv::Mat::operator()(cv::Rect_
> const&) const]+0x1b): undefined reference to cv::Mat::Mat(cv::Mat const&,
> cv::Rect_<int> const&)'
> /tmp/ccDDga1V.o: In functionstd::basic_string, std::allocator >
> cv::CommandLineParser::get, std::allocator > >(std::basic_string,
> std::allocator > const&, bool)':
> face-detect.cpp:(.text._ZN2cv17CommandLineParser3getISsEET_RKSsb[std::basic_string,
> std::allocator > cv::CommandLineParser::get, std::allocator >
> 
> > (std::basic_string, std::allocator > const&, bool)]+0x1b): undefined
> > reference to cv::CommandLineParser::has(std::basic_string<char,
> > std::char_traits<char>, std::allocator<char> > const&)'
> > face-detect.cpp:(.text._ZN2cv17CommandLineParser3getISsEET_RKSsb[std::basic_string<char,
> > std::char_traits<char>, std::allocator<char> >
> > cv::CommandLineParser::get<std::basic_string<char, std::char_traits<char>,
> > std::allocator<char> > >(std::basic_string<char, std::char_traits<char>,
> > std::allocator<char> > const&, bool)]+0x48): undefined reference tocv::CommandLineParser::getString(std::basic_string,
> > std::allocator > const&)'
> > face-detect.cpp:(.text._ZN2cv17CommandLineParser3getISsEET_RKSsb[std::basic_string,
> > std::allocator > cv::CommandLineParser::get, std::allocator >
> > (std::basic_string, std::allocator > const&, bool)]+0x6c): undefined
> > reference to `std::basic_string, std::allocator >
> > cv::CommandLineParser::analizeValue, std::allocator > >(std::basic_string,
> > std::allocator > const&, bool)'
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bsdnoobz/web-based-face-detect/issues/1
> .

## 

http://bsd-noobz.com - Web performance, Programming, Agile

**Comment by dokuboyejo** [comment]
I am getting something similar on OpenCV 2.9
XXXXXXX@A2O4-UBUNTU:~/workspace/eclipse/TestOpenCV C++/src$ g++ houghlines_me.cpp 'pkg-config --cflags opencv`
/tmp/ccjUYxjD.o: In function`main':
houghlines_me.cpp:(.text+0x83): undefined reference to `cv::imread(cv::String const&, int)'
houghlines_me.cpp:(.text+0x127): undefined reference to`cv::_OutputArray::_OutputArray(cv::Mat&)'
houghlines_me.cpp:(.text+0x13f): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
houghlines_me.cpp:(.text+0x167): undefined reference to`cv::cvtColor(cv::_InputArray const&, cv::_OutputArray const&, int, int)'
houghlines_me.cpp:(.text+0x175): undefined reference to `cv::_InputArray::~_InputArray()'
houghlines_me.cpp:(.text+0x183): undefined reference to`cv::_OutputArray::~_OutputArray()'
houghlines_me.cpp:(.text+0x19b): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
houghlines_me.cpp:(.text+0x1b3): undefined reference to`cv::_InputArray::_InputArray(cv::Mat const&)'
houghlines_me.cpp:(.text+0x1ef): undefined reference to `cv::Canny(cv::_InputArray const&, cv::_OutputArray const&, double, double, int, bool)'
houghlines_me.cpp:(.text+0x1fd): undefined reference to`cv::_InputArray::~_InputArray()'
houghlines_me.cpp:(.text+0x20b): undefined reference to `cv::_OutputArray::~_OutputArray()'
houghlines_me.cpp:(.text+0x223): undefined reference to`cv::_OutputArray::_OutputArray(cv::Mat&)'
houghlines_me.cpp:(.text+0x23b): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
houghlines_me.cpp:(.text+0x263): undefined reference to`cv::cvtColor(cv::_InputArray const&, cv::_OutputArray const&, int, int)'
houghlines_me.cpp:(.text+0x271): undefined reference to `cv::_InputArray::~_InputArray()'
houghlines_me.cpp:(.text+0x27f): undefined reference to`cv::_OutputArray::~_OutputArray()'
houghlines_me.cpp:(.text+0x2b7): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
houghlines_me.cpp:(.text+0x2fb): undefined reference to`cv::HoughLinesP(cv::_InputArray const&, cv::_OutputArray const&, double, double, int, double, double)'
houghlines_me.cpp:(.text+0x309): undefined reference to `cv::_InputArray::~_InputArray()'
houghlines_me.cpp:(.text+0x317): undefined reference to`cv::_OutputArray::~_OutputArray()'
houghlines_me.cpp:(.text+0x426): undefined reference to `cv::line(cv::Mat&, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int)'
houghlines_me.cpp:(.text+0x458): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
houghlines_me.cpp:(.text+0x47d): undefined reference to`cv::imshow(cv::String const&, cv::_InputArray const&)'
houghlines_me.cpp:(.text+0x493): undefined reference to `cv::_InputArray::~_InputArray()'
houghlines_me.cpp:(.text+0x4a8): undefined reference to`cv::_InputArray::_InputArray(cv::Mat const&)'
houghlines_me.cpp:(.text+0x4cd): undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
houghlines_me.cpp:(.text+0x4e3): undefined reference to`cv::_InputArray::~_InputArray()'
houghlines_me.cpp:(.text+0x4ef): undefined reference to `cv::waitKey(int)'
houghlines_me.cpp:(.text+0x56a): undefined reference to`cv::_InputArray::~_InputArray()'
houghlines_me.cpp:(.text+0x57c): undefined reference to `cv::_OutputArray::~_OutputArray()'
houghlines_me.cpp:(.text+0x591): undefined reference to`cv::_InputArray::~_InputArray()'
houghlines_me.cpp:(.text+0x5a3): undefined reference to `cv::_OutputArray::~_OutputArray()'
houghlines_me.cpp:(.text+0x5b8): undefined reference to`cv::_InputArray::~_InputArray()'
houghlines_me.cpp:(.text+0x5ca): undefined reference to `cv::_OutputArray::~_OutputArray()'
houghlines_me.cpp:(.text+0x5dc): undefined reference to`cv::_InputArray::~_InputArray()'
houghlines_me.cpp:(.text+0x5ee): undefined reference to `cv::_OutputArray::~_OutputArray()'
houghlines_me.cpp:(.text+0x60c): undefined reference to`cv::_InputArray::~_InputArray()'
houghlines_me.cpp:(.text+0x62a): undefined reference to `cv::_InputArray::~_InputArray()'
/tmp/ccjUYxjD.o: In function`cv::String::String(char const_)':
houghlines_me.cpp:(.text._ZN2cv6StringC2EPKc[_ZN2cv6StringC5EPKc]+0x3b): undefined reference to `cv::String::allocate(unsigned int)'
/tmp/ccjUYxjD.o: In function`cv::String::~String()':
houghlines_me.cpp:(.text._ZN2cv6StringD2Ev[_ZN2cv6StringD5Ev]+0xd): undefined reference to `cv::String::deallocate()'
/tmp/ccjUYxjD.o: In function`cv::Mat::~Mat()':
houghlines_me.cpp:(.text._ZN2cv3MatD2Ev[_ZN2cv3MatD5Ev]+0x2b): undefined reference to `cv::fastFree(void_)'
/tmp/ccjUYxjD.o: In function `cv::Mat::release()':
houghlines_me.cpp:(.text._ZN2cv3Mat7releaseEv[cv::Mat::release()]+0x3b): undefined reference to`cv::Mat::deallocate()'
/tmp/ccjUYxjD.o: In function `cv::_OutputArray::_OutputArray<cv::Vec<int, 4> >(std::vector<cv::Vec<int, 4>, std::allocator<cv::Vec<int, 4> > >&)':
houghlines_me.cpp:(.text._ZN2cv12_OutputArrayC2INS_3VecIiLi4EEEEERSt6vectorIT_SaIS5_EE[_ZN2cv12_OutputArrayC5INS_3VecIiLi4EEEEERSt6vectorIT_SaIS5_EE]+0x1d): undefined reference to`vtable for cv::_OutputArray'
/tmp/ccjUYxjD.o: In function `cv::_InputArray::_InputArray<cv::Vec<int, 4> >(std::vector<cv::Vec<int, 4>, std::allocator<cv::Vec<int, 4> > > const&)':
houghlines_me.cpp:(.text._ZN2cv11_InputArrayC2INS_3VecIiLi4EEEEERKSt6vectorIT_SaIS5_EE[_ZN2cv11_InputArrayC5INS_3VecIiLi4EEEEERKSt6vectorIT_SaIS5_EE]+0xb): undefined reference to`vtable for cv::_InputArray'
collect2: ld returned 1 exit status

**Comment by dmitry** [comment]
@dokuboyejo Try out:

```
g++ `pkg-config --cflags --libs opencv` houghlines_me.cpp `pkg-config --libs opencv`
```

**Comment by chebhou** [comment]
I had this error: undefined reference to `cv::CascadeClassifier::CascadeClassifier()'
while compiling in Qt because of a missing library " libopencv_objdetect " ,once i added it the problem is solved.  
in your project file add :
LIBS += -LC:\DevProgrames\OpenCV24\opencv_bin\bin \
    -llibopencv_core249d \
    -llibopencv_highgui249d \
    -llibopencv_imgproc249d \
    -llibopencv_features2d249d \
    -llibopencv_calib3d249d \
    -llibopencv_objdetect249d

249 <--- this number indicates the version so it may be different for you.

**Comment by stephan2014** [comment]
Hi Nash,

I have tried your Script with the Version 2.4.8 of opencv but I get erros.

If I check: pkg-config --modversion opencv
I get: 2.4.8

g++ `pkg-config --cflags --libs opencv` face-detect.cpp -o face-detect

The Result is:

face-detect.cpp:(.text+0x3a): undefined reference to `cv::CommandLineParser::CommandLineParser(int, char const* const*, char const*)'
face-detect.cpp:(.text+0x156): undefined reference to`cv::CascadeClassifier::CascadeClassifier()'
face-detect.cpp:(.text+0x182): undefined reference to `cv::CascadeClassifier::load(std::string const&)'
face-detect.cpp:(.text+0x1b2): undefined reference to`cv::format(char const_, ...)'
face-detect.cpp:(.text+0x1fd): undefined reference to `cv::imread(std::string const&, int)'
face-detect.cpp:(.text+0x229): undefined reference to`cv::format(char const_, ...)'
face-detect.cpp:(.text+0x27e): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
face-detect.cpp:(.text+0x297): undefined reference to`cv::_InputArray::_InputArray(cv::Mat const&)'
face-detect.cpp:(.text+0x2b7): undefined reference to `cv::cvtColor(cv::_InputArray const&, cv::_OutputArray const&, int, int)'
face-detect.cpp:(.text+0x2d0): undefined reference to`cv::_OutputArray::_OutputArray(cv::Mat&)'
face-detect.cpp:(.text+0x2e9): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
face-detect.cpp:(.text+0x302): undefined reference to`cv::equalizeHist(cv::_InputArray const&, cv::_OutputArray const&)'
face-detect.cpp:(.text+0x382): undefined reference to `cv::CascadeClassifier::detectMultiScale(cv::Mat const&, std::vector<cv::Rect_<int>, std::allocatorcv::Rect_<int > >&, double, int, int, cv::Size_<int>, cv::Size_<int>)'
face-detect.cpp:(.text+0x3bf): undefined reference to `cv::format(char const*, ...)'
face-detect.cpp:(.text+0x440): undefined reference to`cv::format(char const_, ...)'
face-detect.cpp:(.text+0x504): undefined reference to `cv::rectangle(cv::Mat&, cv::Rect_<int>, cv::Scalar_<double> const&, int, int, int)'
face-detect.cpp:(.text+0x54c): undefined reference to`cv::_InputArray::_InputArray(cv::Mat const&)'
face-detect.cpp:(.text+0x56c): undefined reference to `cv::imwrite(std::string const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
face-detect.cpp:(.text+0x5b2): undefined reference to`cv::_InputArray::_InputArray(cv::Mat const&)'
face-detect.cpp:(.text+0x5d2): undefined reference to `cv::imwrite(std::string const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
face-detect.cpp:(.text+0x62d): undefined reference to`cv::format(char const_, ...)'
face-detect.cpp:(.text+0x6dc): undefined reference to `cv::CascadeClassifier::~CascadeClassifier()'
face-detect.cpp:(.text+0x8bc): undefined reference to`cv::CascadeClassifier::~CascadeClassifier()'
/tmp/ccerD6SI.o: In function `cv::Mat::~Mat()':
face-detect.cpp:(.text._ZN2cv3MatD2Ev[_ZN2cv3MatD5Ev]+0x39): undefined reference to`cv::fastFree(void*)'
/tmp/ccerD6SI.o: In function `cv::Mat::clone() const':
face-detect.cpp:(.text._ZNK2cv3Mat5cloneEv[_ZNK2cv3Mat5cloneEv]+0x2c): undefined reference to`cv::_OutputArray::_OutputArray(cv::Mat&)'
face-detect.cpp:(.text._ZNK2cv3Mat5cloneEv[_ZNK2cv3Mat5cloneEv]+0x3f): undefined reference to `cv::Mat::copyTo(cv::_OutputArray const&) const'
/tmp/ccerD6SI.o: In function`cv::Mat::release()':
face-detect.cpp:(.text._ZN2cv3Mat7releaseEv[_ZN2cv3Mat7releaseEv]+0x47): undefined reference to `cv::Mat::deallocate()'
/tmp/ccerD6SI.o: In function`cv::Mat::operator()(cv::Rect_<int> const&) const':
face-detect.cpp:(.text._ZNK2cv3MatclERKNS_5Rect_IiEE[_ZNK2cv3MatclERKNS_5Rect_IiEE]+0x27): undefined reference to `cv::Mat::Mat(cv::Mat const&, cv::Rect_<int> const&)'
/tmp/ccerD6SI.o: In function `std::string cv::CommandLineParser::get<std::string>(std::string const&, bool)':
face-detect.cpp:(.text._ZN2cv17CommandLineParser3getISsEET_RKSsb[_ZN2cv17CommandLineParser3getISsEET_RKSsb]+0x29): undefined reference to`cv::CommandLineParser::has(std::string const&)'
face-detect.cpp:(.text._ZN2cv17CommandLineParser3getISsEET_RKSsb[_ZN2cv17CommandLineParser3getISsEET_RKSsb]+0x55): undefined reference to `cv::CommandLineParser::getString(std::string const&)'
face-detect.cpp:(.text._ZN2cv17CommandLineParser3getISsEET_RKSsb[_ZN2cv17CommandLineParser3getISsEET_RKSsb]+0x6d): undefined reference to`std::string cv::CommandLineParser::analyzeValuestd::string(std::string const&, bool)'
collect2: error: ld returned 1 exit status

Plese help me :-)

**Comment by growlead** [comment]
Here the solution 

```
g++ `pkg-config --cflags opencv` face-detect.cpp `pkg-config --libs opencv` -o face-detect
```

**Comment by ashokbugude** [comment]
I tried all the above methods with opencv 2.4.9 , but i get below errors

peopleDetect.cpp:(.text+0x133): undefined reference to `cv::CommandLineParser::CommandLineParser(int, char const* const*, cv::String const&)'
peopleDetect.cpp:(.text+0x16f): undefined reference to`cv::CommandLineParser::about(cv::String const&)'
peopleDetect.cpp:(.text+0x1ab): undefined reference to `cv::CommandLineParser::has(cv::String const&) const'
peopleDetect.cpp:(.text+0x1d1): undefined reference to`cv::CommandLineParser::printMessage() const'
peopleDetect.cpp:(.text+0x1ea): undefined reference to `cv::CommandLineParser::check() const'
peopleDetect.cpp:(.text+0x200): undefined reference to`cv::CommandLineParser::printErrors() const'
peopleDetect.cpp:(.text+0x49a): undefined reference to `cv::softcascade::Detector::Detector(double, double, int, int)'
peopleDetect.cpp:(.text+0x554): undefined reference to`cv::_InputArray::~_InputArray()'
peopleDetect.cpp:(.text+0x5d1): undefined reference to `cv::FileStorage::FileStorage(cv::String const&, int, cv::String const&)'
peopleDetect.cpp:(.text+0x68c): undefined reference to`cv::softcascade::Detector::Detector(double, double, int, int)'
peopleDetect.cpp:(.text+0x6b4): undefined reference to `cv::softcascade::Detector::~Detector()'
peopleDetect.cpp:(.text+0x6e6): undefined reference to`cv::softcascade::Detector::load(cv::FileNode const&)'
peopleDetect.cpp:(.text+0x804): undefined reference to `cv::glob(cv::String, std::vector<cv::String, std::allocator<cv::String> >&, bool)'
peopleDetect.cpp:(.text+0x92a): undefined reference to`cv::imread(cv::String const&, int)'
peopleDetect.cpp:(.text+0xd50): undefined reference to `cv::softcascade::Detector::detect(cv::_InputArray const&, cv::_InputArray const&, std::vector<cv::softcascade::Detection, std::allocator<cv::softcascade::Detection> >&) const'
peopleDetect.cpp:(.text+0xd5f): undefined reference to`cv::_InputArray::~_InputArray()'
peopleDetect.cpp:(.text+0x1016): undefined reference to `cv::putText(cv::Mat&, cv::String const&, cv::Point_<int>, int, double, cv::Scalar_<double>, int, int, bool)'
peopleDetect.cpp:(.text+0x11b5): undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
peopleDetect.cpp:(.text+0x11e2): undefined reference to`cv::_InputArray::~_InputArray()'
peopleDetect.cpp:(.text+0x1258): undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
peopleDetect.cpp:(.text+0x1276): undefined reference to`cv::_InputArray::~_InputArray()'
peopleDetect.cpp:(.text+0x1328): undefined reference to `cv::softcascade::Detector::~Detector()'
peopleDetect.cpp:(.text+0x14a3): undefined reference to`cv::_InputArray::~_InputArray()'
peopleDetect.cpp:(.text+0x1601): undefined reference to `cv::_InputArray::~_InputArray()'
peopleDetect.cpp:(.text+0x169d): undefined reference to`cv::_InputArray::~_InputArray()'
peopleDetect.cpp:(.text+0x16d9): undefined reference to `cv::_InputArray::~_InputArray()'
peopleDetect.cpp:(.text+0x1765): undefined reference to`cv::softcascade::Detector::~Detector()'
/tmp/ccLW3md5.o: In function `cv::String::String(char const*)':
peopleDetect.cpp:(.text._ZN2cv6StringC2EPKc[_ZN2cv6StringC5EPKc]+0x4d): undefined reference to`cv::String::allocate(unsigned long)'
/tmp/ccLW3md5.o: In function `cv::String::~String()':
peopleDetect.cpp:(.text._ZN2cv6StringD2Ev[_ZN2cv6StringD5Ev]+0x14): undefined reference to`cv::String::deallocate()'
/tmp/ccLW3md5.o: In function `cv::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
peopleDetect.cpp:(.text._ZN2cv6StringC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN2cv6StringC5ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x69): undefined reference to`cv::String::allocate(unsigned long)'
/tmp/ccLW3md5.o: In function `cv::String cv::CommandLineParser::get<cv::String>(cv::String const&, bool) const':
peopleDetect.cpp:(.text._ZNK2cv17CommandLineParser3getINS_6StringEEET_RKS2_b[_ZNK2cv17CommandLineParser3getINS_6StringEEET_RKS2_b]+0x51): undefined reference to`cv::CommandLineParser::getByName(cv::String const&, bool, int, void_) const'
/tmp/ccLW3md5.o: In function `int cv::CommandLineParser::get<int>(cv::String const&, bool) const':
peopleDetect.cpp:(.text._ZNK2cv17CommandLineParser3getIiEET_RKNS_6StringEb[_ZNK2cv17CommandLineParser3getIiEET_RKNS_6StringEb]+0x47): undefined reference to`cv::CommandLineParser::getByName(cv::String const&, bool, int, void_) const'
/tmp/ccLW3md5.o: In function `float cv::CommandLineParser::get<float>(cv::String const&, bool) const':
peopleDetect.cpp:(.text._ZNK2cv17CommandLineParser3getIfEET_RKNS_6StringEb[_ZNK2cv17CommandLineParser3getIfEET_RKNS_6StringEb]+0x49): undefined reference to`cv::CommandLineParser::getByName(cv::String const&, bool, int, void*) const'
collect2: error: ld returned 1 exit status
